name: Claude Code

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

# Add permissions for OIDC token
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  claude:
    runs-on: self-hosted  # Changed to use self-hosted runner
    # Only run for comments that mention @claude or issues with @claude
    if: contains(github.event.comment.body, '@claude') || (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Claude Code
        uses: anthropics/claude-code-action@v0
        with:
          anthropic_model: "claude-sonnet-4-20250514"
          # Using direct ANTHROPIC_API_KEY (no renaming)
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}