name: Claude Basic Test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Test Claude API directly
        env:
          API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          cat > test_claude_direct.py << 'EOL'
          import os
          import requests
          import json
          import sys
          
          def test_claude_api():
              api_key = os.environ.get("API_KEY")
              
              if not api_key:
                  print("Error: API_KEY environment variable not set")
                  sys.exit(1)
              
              print(f"API Key length: {len(api_key)} characters")
              print(f"API Key first 5 chars: {api_key[:5]}...")
              print(f"API Key last 5 chars: ...{api_key[-5:]}")
              
              headers = {
                  "Authorization": f"Bearer {api_key}",
                  "Content-Type": "application/json"
              }
              
              data = {
                  "model": "claude-3-sonnet-20240620",
                  "messages": [
                      {
                          "role": "user",
                          "content": "Say hello!"
                      }
                  ],
                  "max_tokens": 10
              }
              
              try:
                  # First try the standard Anthropic API
                  api_url = "https://api.anthropic.com/v1/messages"
                  print(f"Trying standard Anthropic API at {api_url}")
                  response = requests.post(api_url, headers=headers, json=data, timeout=10)
                  
                  if response.status_code == 200:
                      print("✓ Standard API connection successful!")
                      result = response.json()
                      print(f"Response: {json.dumps(result, indent=2)}")
                      return True
                  else:
                      print(f"✗ Standard API failed with status code: {response.status_code}")
                      print(f"Response: {response.text}")
                      
                      # Try corporate endpoint as fallback
                      print("\nTrying corporate endpoint as fallback...")
                      api_url = "https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions"
                      response = requests.post(api_url, headers=headers, json=data, timeout=10)
                      
                      if response.status_code == 200:
                          print("✓ Corporate API connection successful!")
                          result = response.json()
                          print(f"Response: {json.dumps(result, indent=2)}")
                          return True
                      else:
                          print(f"✗ Corporate API failed with status code: {response.status_code}")
                          print(f"Response: {response.text}")
                          return False
                      
              except Exception as e:
                  print(f"Error: {str(e)}")
                  return False
          
          if __name__ == "__main__":
              success = test_claude_api()
              if not success:
                  sys.exit(1)
          EOL
          
          python test_claude_direct.py