name: Claude Code

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      bug_title:
        description: 'Bug Title'
        required: true
        type: string
      bug_description:
        description: 'Bug Description'
        required: true
        type: string

# Add permissions for OIDC token
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  claude:
    runs-on: self-hosted  # Changed to use self-hosted runner
    # Run for comments that mention @claude, issues with @claude, or workflow_dispatch
    if: contains(github.event.comment.body, '@claude') || (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Set up environment before running Claude
      - name: Set up Claude environment
        run: |
          echo "Setting up Claude environment variables"
          echo "ANTHROPIC_BASE_URL=https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions" >> $GITHUB_ENV
          echo "ANTHROPIC_API_BASE=https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions" >> $GITHUB_ENV
          echo "CLAUDE_CODE_USE_DIRECT_COMPLETION_ENDPOINT=1" >> $GITHUB_ENV
          # Set the model identifier directly in environment variables
          echo "ANTHROPIC_MODEL=claude-sonnet-4-20250514" >> $GITHUB_ENV
          echo "Environment variables set"
      
      - name: Claude Code
        uses: anthropics/claude-code-action@v0
        env:
          ANTHROPIC_BASE_URL: https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions
          ANTHROPIC_API_BASE: https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions
          ANTHROPIC_MODEL: claude-sonnet-4-20250514
          CLAUDE_CODE_USE_DIRECT_COMPLETION_ENDPOINT: "1"
          CLAUDE_CODE_SKIP_BEDROCK_AUTH: "1"
          CLAUDE_CODE_USE_BEDROCK: "1"
        with:
          mode: agent
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            A bug has been reported in our iOS Netflix clone app:
            
            **Bug Title:** ${{ inputs.bug_title || github.event.issue.title || github.event.comment.body }}
            **Bug Description:** ${{ inputs.bug_description || github.event.issue.body || github.event.comment.body }}
            
            Please analyze this bug and provide code fixes for the iOS Swift application.