name: Claude Code

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

# Add permissions for OIDC token
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  claude:
    runs-on: ubuntu-latest
    # Only run for comments that mention @claude or issues with @claude
    if: contains(github.event.comment.body, '@claude') || (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Claude Code
        uses: anthropics/claude-code-action@v0
        with:
          # Use API key directly instead of Bedrock
          anthropic_api_key: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          # Custom configuration
          claude_env: |
            {
              "ANTHROPIC_API_URL": "https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions",
              "ANTHROPIC_API_VERSION": "2023-06-01"
            }